### ISSUE TITLE
Option to disable logging in nzpy

### ISSUE THREAD

**Issue by shabbir10july** [IBM/nzpy#23]
Raising this on behalf of @mderoy

nzpy uses the default loglevel of 0. 
Can we get an option to disable logging entirely? maybe something like logLevel=-1

workaround I'm using is to set a nullhandler before connecting:

```
            logging.getLogger().addHandler(logging.NullHandler())
            self.connection = nzpy.connect(user="admin", unix_sock='/tmp/.s.PGSQL.5480', database="system")

```

**Comment by tshifflett90** [comment]
Or can we get the option to save the log file somewhere? Like a LOGDIR in nz load.

**Comment by aniket-s-kulkarni** [comment]
Here's a proposal 

## Logging
You can set logLevel to control logging verbosity. In order to enable logging, you need to pass logLevel in your application using connection string.

```python
conn = nzpy.connect(user="admin", password="password",host='localhost', port=5480,
                       database="db1", securityLevel=0,
                        logLevel=logging.DEBUG)
```

In addition there are 3 more options to control logging. One or more of these can be specified using `logOptions` argument to `nzpy.connect`

1. Inherit the logging settings of the parent / caller

This is `nzpy.LogOptions.Inherit` option. The logging from nzpy is propgated to the logging configured by the parent

```python
logging.basicConfig(filename="myapplication.log")
logging.info("...")
# ..
conn = nzpy.connect(user="admin", password="password",host='localhost', port=5480,
                       database="db1", securityLevel=0,
                       logOptions=nzpy.LogOptions.Inherit)

# .. all of nzpy logs will go to the inherited log settings
```

2. Logging details to a logfile

This is `nzpy.LogOptions.Logfile` option. The logging from nzpy is sent to 'nzpy.log' in the current directory. The file is rotated after 10 G. If `nzpy.LogOptions.Inherit` is set as well then both are honored

```python
logging.basicConfig(filename="myapplication.log")
logging.info("...")
# ..
conn1 = nzpy.connect(user="admin", password="password",host='localhost', port=5480,
                       database="db1", securityLevel=0,
                       logOptions=nzpy.LogOptions.Logfile)

# .. all of conn1's nzpy logs will go to the nzpy.log only

conn2 = nzpy.connect(user="admin", password="password",host='localhost', port=5480,
                       database="db1", securityLevel=0,
                  logOptions=nzpy.LogOptions.Logfile | nzpy.LogOptions.Inherit)

# .. all of conn2's nzpy logs will go to the nzpy.log _and_ to myapplication.log


conn3 = nzpy.connect(user="admin", password="password",host='localhost', port=5480,
                       database="db1", securityLevel=0,
                      logOptions=nzpy.LogOptions.Disabled)
# .. conn3's logging is completely disabled

```

3. Disable nzpy logging

This is `nzpy.LogOptions.Disabled` option

**Comment by joebeeson** [comment]
Logging setup should be left to the application and not the packages -- explicitly configuring the logger is at best a nicety and at worst a hindrance. See the [_Configuring Logging for a Library_](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) from the documentation, specifically this part:

> **Note:** It is strongly advised that you do not add any handlers other than `NullHandler` to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.
